AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mmog-microtx-rs
  MMO Game Micro-transaction API - Rust Version
  
  ADVANTAGES OVER NODE.JS:
  - 128MB memory sufficient (no GC overhead)
  - 5 second timeout (native binary starts instantly)
  - Cold starts ~10-50ms vs 200-800ms for Node.js
  - ~5x smaller deployment package (no node_modules)
  - Lower cost per invocation

Globals:
  Function:
    # ADVANTAGE: Rust needs minimal memory - no GC heap
    MemorySize: 128
    # ADVANTAGE: Fast startup - no interpreter initialization
    Timeout: 5
    # ADVANTAGE: Uses OS-only runtime - just the binary
    Runtime: provided.al2023
    Architectures:
      # ADVANTAGE: ARM64 is cheaper and often faster for Rust
      - arm64
    Environment:
      Variables:
        RUST_LOG: info
        DATABASE_URL: !Sub "postgresql://${DatabaseUser}:${DatabasePassword}@${DatabaseHost}:${DatabasePort}/${DatabaseName}"
        STRIPE_API_KEY: !Ref StripeApiKey
        USE_MOCK_PAYMENTS: !Ref UseMockPayments

Parameters:
  DatabaseHost:
    Type: String
    Description: Aurora PostgreSQL cluster endpoint
  DatabasePort:
    Type: String
    Default: "5432"
  DatabaseName:
    Type: String
    Default: mmog_transactions
  DatabaseUser:
    Type: String
  DatabasePassword:
    Type: String
    NoEcho: true
  StripeApiKey:
    Type: String
    NoEcho: true
    Default: ""
  UseMockPayments:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

Resources:
  # ============================================================================
  # Main Microtransaction Function
  # ADVANTAGE: Single binary deployment - no dependency resolution
  # ============================================================================
  MicrotxFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: mmog-microtx-rs
        # ADVANTAGE: Cargo Lambda handles cross-compilation
        BuildArgs: --release
    Properties:
      FunctionName: mmog-microtx-rs
      Description: Process MMO game micro-transactions (Rust - GA)
      CodeUri: .
      Handler: bootstrap  # ADVANTAGE: Native binary, not script
      # ADVANTAGE: Cold start benchmark comparison
      # Rust: 10-50ms cold start
      # Node.js: 200-800ms cold start
      # That's 4-80x faster!
      Events:
        PurchaseApi:
          Type: Api
          Properties:
            RestApiId: !Ref MicrotxApi
            Path: /purchase
            Method: POST
        TransactionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref MicrotxApi
            Path: /transactions/{playerId}
            Method: GET
        HealthApi:
          Type: Api
          Properties:
            RestApiId: !Ref MicrotxApi
            Path: /health
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Policies:
        - VPCAccessPolicy: {}
        - Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/*"

  # ============================================================================
  # API Gateway
  # ============================================================================
  MicrotxApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: mmog-microtx-rs-api
      StageName: prod
      Description: MMO Game Microtransaction API (Rust - GA)
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # ============================================================================
  # VPC Resources
  # ============================================================================
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Rust Lambda functions
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16

  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mmog/vpc/id
  PrivateSubnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mmog/vpc/subnet1
  PrivateSubnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mmog/vpc/subnet2

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${MicrotxApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt MicrotxFunction.Arn
  FunctionName:
    Description: Lambda function name
    Value: !Ref MicrotxFunction
  # ADVANTAGE: Expose deployment size for comparison
  DeploymentNote:
    Description: Deployment comparison note
    Value: "Rust binary: ~5-10MB | Node.js with node_modules: ~50-100MB"
